version: '3.8'

services:
  app:
    build:
      context: .
      args:
        NODE_ENV: production
        VITE_STRIPE_PUBLIC_KEY: ${VITE_STRIPE_PUBLIC_KEY}
    ports:
      - "8000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - HOST=0.0.0.0
      - VERIFICATION_LOGGING=true
      - DATABASE_URL=${DATABASE_URL}
      - PGSSLMODE=${PGSSLMODE:-require}
      - SESSION_SECRET=${SESSION_SECRET:-your-super-secret-session-key-here-at-least-32-characters-long}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - FROM_EMAIL=${FROM_EMAIL:-uplink@roguesim.com}
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp
      - /app/logs
    volumes:
      - app-data:/app/data:rw

  # Optional: Reverse proxy for SSL termination
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    restart: unless-stopped

volumes:
  app-data:
    driver: local
