version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://rogueuser:${DB_PASSWORD:-nZrdLEehQFVTZ9ogVZXxmfpKOe68thkQTtwuVXaokQM=}@postgres:5432/roguesim
      - SESSION_SECRET=${SESSION_SECRET:-your-super-secret-session-key-here}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: roguesim-postgres
    environment:
      - POSTGRES_DB=roguesim
      - POSTGRES_USER=rogueuser
      - POSTGRES_PASSWORD=${DB_PASSWORD:-nZrdLEehQFVTZ9ogVZXxmfpKOe68thkQTtwuVXaokQM=}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  # Optional: Database management UI
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: roguesim-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=uplink@roguesim.com
      - PGADMIN_DEFAULT_PASSWORD=roguesim123
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: 