version: "3.8"

services:
  app:
    build:
      context: .
      args:
        NODE_ENV: production
        # Vite (and any client) envs are BAKED at build time:
        VITE_STRIPE_PUBLIC_KEY: ${VITE_STRIPE_PUBLIC_KEY}
    ports:
      - "8000:5000"
    env_file:
      - ./.env
    environment:
      NODE_ENV: production
      PORT: 5000
      HOST: 0.0.0.0
      DATABASE_URL: ${DATABASE_URL}
      PGSSLMODE: ${PGSSLMODE:-require}   # For Neon/managed PG
      SESSION_SECRET: ${SESSION_SECRET:-change-me-32chars-min}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      FROM_EMAIL: ${FROM_EMAIL:-noreply@yourdomain.com}
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:5000/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    # Uncomment if your app can run non-root + read-only
    # user: "1000:1000"
    # read_only: true
    # tmpfs: ["/tmp"]
    # security_opt: ["no-new-privileges:true"]
    # cap_drop: ["ALL"]
