version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: roguesim-postgres
    environment:
      POSTGRES_DB: roguesim
      POSTGRES_USER: roguesim_user
      POSTGRES_PASSWORD: roguesim_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  # Optional: Database management UI
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: roguesim-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@roguesim.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data: 