#!/bin/bash

echo "🌐 RogueSim Domain Setup for roguesim.com"
echo "=========================================="

echo "✅ Your app is confirmed working on: http://49.13.197.91:8080"
echo ""

echo "🔥 CLOUDFLARE SETUP INSTRUCTIONS:"
echo "=================================="
echo ""
echo "1. 📱 Go to Cloudflare Dashboard → roguesim.com → DNS Records"
echo ""
echo "2. ➕ Add these DNS records:"
echo "   Type: A"
echo "   Name: @"
echo "   IPv4: 49.13.197.91"
echo "   Proxy: 🟠 Proxied (Orange Cloud ON)"
echo ""
echo "   Type: A" 
echo "   Name: www"
echo "   IPv4: 49.13.197.91"
echo "   Proxy: 🟠 Proxied (Orange Cloud ON)"
echo ""

echo "3. ⚙️ Configure Cloudflare for Port 8080:"
echo ""
echo "   Go to: SSL/TLS → Origin Server"
echo "   Set Origin Server: 49.13.197.91:8080"
echo ""
echo "   Go to: Network → Network Settings"
echo "   Enable: HTTP2 to Origin"
echo ""

echo "4. 🔧 Page Rules (if needed):"
echo "   URL: roguesim.com/*"
echo "   Setting: Resolve Override → 49.13.197.91:8080"
echo ""

echo "5. 🧪 Test your domain:"
echo "   • http://roguesim.com"
echo "   • https://roguesim.com"
echo ""

echo "⚠️  IMPORTANT: Cloudflare only proxies certain ports!"
echo "   Port 8080 should work, but if not, see Option 2 below."
echo ""

echo "🚀 OPTION 2: Switch to Standard Port 80"
echo "======================================="
echo ""
echo "If port 8080 doesn't work with Cloudflare, run this:"
echo ""
echo "# Stop whatever is using port 80"
echo "systemctl stop apache2 nginx lighttpd || true"
echo "docker stop \$(docker ps -q) || true"
echo ""
echo "# Update to use port 80"
echo "sed -i 's/\"8080:5000\"/\"80:5000\"/g' docker-compose.yml"
echo "docker-compose up -d"
echo ""
echo "Then your domain will work perfectly with standard HTTP/HTTPS."
echo ""

echo "🌐 Expected Results:"
echo "==================="
echo "After setup, these should all work:"
echo "• http://roguesim.com → Your RogueSim app"
echo "• https://roguesim.com → Your RogueSim app (with SSL)"
echo "• www.roguesim.com → Your RogueSim app"
echo ""

echo "🔍 Troubleshooting:"
echo "==================="
echo "If domain doesn't work:"
echo "1. Wait 5-10 minutes for DNS propagation"
echo "2. Check Cloudflare DNS → Should show 'Proxied'"
echo "3. Try switching to port 80 (Option 2 above)"
echo "4. Use dig roguesim.com to verify DNS"
echo ""

echo "✅ Your server is ready! Just configure Cloudflare DNS now." 